# Generated by Django 6.1.1 on 2026-09-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='passengers.flight'),
        ),
    ]
