# Generated by Django 6.1.1 on 2026-09-22 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0003_passenger_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baggage_tag', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('declared', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baggage', to='passengers.passenger')),
            ],
        ),
    ]
