# Generated by Django 6.1.1 on 2026-09-22 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0004_baggage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('result', models.CharField(choices=[('not_set', 'Not Set'), ('cleared', 'Cleared'), ('for_assessment', 'For Assessment'), ('held', 'Held'), ('seized', 'Seized')], default='not_set', max_length=30)),
                ('findings', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baggage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inspection', to='passengers.baggage')),
            ],
        ),
    ]
