# Generated by Django 6.1.1 on 2026-09-25 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0007_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('held', 'Held'), ('referred', 'Referred')], default='pending', max_length=20)),
                ('clearance_reference', models.CharField(max_length=50, unique=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baggage', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clearance', to='passengers.baggage')),
            ],
        ),
    ]
