# Generated by Django 6.1.1 on 2026-09-25 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0008_clearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_reference', models.CharField(max_length=50, unique=True)),
                ('case_type', models.CharField(choices=[('held', 'Held'), ('seizure', 'Seizure'), ('restricted_item', 'Restricted Item'), ('prohibited_item', 'Prohibited Item'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baggage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='passengers.baggage')),
            ],
        ),
    ]
