# Generated by Django 6.0.2 on 2026-10-01 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0011_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('inspection', 'Inspection Document'), ('assessment', 'Assessment Document'), ('payment', 'Payment Document'), ('clearance', 'Clearance Document'), ('case', 'Case Document'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='boc_naia/documents/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baggage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='passengers.baggage')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
