# Generated by Django 6.1.1 on 2026-10-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0012_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(default=1, editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
