# Generated by Django 6.1.1 on 2026-10-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0013_document_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='new_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
